os: linux
language: cpp
dist: bionic

branches:
  only:
  - master

jobs:
  fast_finish: true
  include:
  - compiler: gcc
    env: COMPILER=g++ CXX=g++
  - compiler: clang
    env: COMPILER=clang++

addons:
  apt:
    packages:
      - build-essential
      - git-core
      - cmake
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
      - libsqlcipher-dev
      - qtbase5-dev
      - qttools5-dev
      - libqt5svg5

script:
- mkdir build
- mkdir build_cipher
- mkdir appbuild
- mkdir appdir
- cd build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON -DFORCE_INTERNAL_QSCINTILLA=ON ..
- make
- ctest -V
- cd ../build_cipher
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=1 ..
- make
- ctest -V
- cd ../appbuild
- cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr -Wno-dev -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=1 -DSQLITE_ENABLE_JSON1=1 ..
- make install
- cd ..
- git rev-list master --count
- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
- export VERSION=$(printf "master-`git rev-list HEAD --count`-` git -C . rev-parse --short HEAD`")
- ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
- mv -v DB_Browser_for_SQLite*.AppImage DB_Browser_for_SQLite-$VERSION.AppImage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - chmod a+x upload.sh
  - UPLOADTOOL_ISPRERELEASE=true ./upload.sh DB_Browser_for_SQLite*.AppImage*

notifications:
  email:
   recipients:
   - github@mkleusberg.de
   - innermous@gmail.com
   - justin@postgresql.org
   - mgrojo@gmail.com
   on_success: never
   on_failure: always
  slack:
   secure: ax5bu7ySF+wlG0pCmQqyzvaurzQt2yLnp/u4KajyFCgWZKOwcvElndjhvW8bIRNgWrGP8TVPkosHhwGucFQNjJq5hHJIbuPzfBTIbITCVbKJNRqeqL0QXlKLwMTejX9AUYwzzJ3xTTj8rZn/UMocsiCy7uPuK1v/5BhZfEr3BBU=
