language: cpp
sudo: required
dist: xenial

branches:
 # only:
#  - master

# env:
#   - ARCH=x86_64 DOCKER_IMAGE=amd64/ubuntu:trusty
#   - ARCH=i686 DOCKER_IMAGE=i386/ubuntu:trusty

matrix:
  fast_finish: true
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env: COMPILER=g++-5 CXX=g++-5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
        packages:
        - clang-3.8
    env: COMPILER=clang++-3.8

before_install:
- sudo apt-get update -qq
- sudo apt-get --force-yes install build-essential git-core cmake libsqlite3-dev qt5-default qttools5-dev-tools libsqlcipher-dev qtbase5-dev libantlr-dev libqt5scintilla2-dev libqcustomplot-dev qttools5-dev
#- QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
#- source $QT_ENV_SCRIPT

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
- mkdir build
- mkdir build_cipher
- mkdir appbuild
- mkdir appdir
- cd build
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON ..
- make
- ctest -V
- cd ../build_cipher
- cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_TESTING=ON -Dsqlcipher=1 ..
- make
- ctest -V
- cd ../appbuild
- cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr -Wno-dev -Dsqlcipher=1 ..
- make install
- cd ..
- wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
#- unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
- export VERSION=$(printf "`cat currentrelease | head -n 1 `-`git rev-list master --count`-` git -C . rev-parse --short HEAD`")    #$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
- ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage


after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh DB_Browser_for_SQLite*.AppImage*

#notifications:
 # email:
  #  recipients:
  #  - mkleusberg@gmail.com
   # - innermous@gmail.com
   # - justin@postgresql.org
   # - mgrojo@gmail.com
   # on_success: never
   # on_failure: always
  #slack:
   # secure: ax5bu7ySF+wlG0pCmQqyzvaurzQt2yLnp/u4KajyFCgWZKOwcvElndjhvW8bIRNgWrGP8TVPkosHhwGucFQNjJq5hHJIbuPzfBTIbITCVbKJNRqeqL0QXlKLwMTejX9AUYwzzJ3xTTj8rZn/UMocsiCy7uPuK1v/5BhZfEr3BBU=
