name: Build - macOS

on:
  workflow_call:
    inputs:
      NIGHTLY:
        default: false
        type: boolean

jobs:
  build:
    name: ${{ matrix.os }} - SQLCipher ${{ matrix.sqlcipher }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        sqlcipher: ["0", "1"]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uninstall Mono, which is included by default in GitHub-hosted macOS runners,
      # as it interferes with referencing our own compiled SQLite libraries.
      - name: Uninstall Mono
        run: |
          sudo rm -rfv /Library/Frameworks/Mono.framework
          sudo pkgutil --forget com.xamarin.mono-MDK.pkg
          sudo rm /etc/paths.d/mono-commands

      - name: Install dependencies
        run: |
          brew update
          brew tap sqlitebrowser/tap
          brew unlink openssl@3
          brew install sqlb-openssl@3
          brew install sqlb-qt@5 sqlb-sqlcipher sqlb-sqlite ninja
          npm install -g appdmg

      - name: Install SQLite
        run: |
          brew install autoconf automake libtool
          git clone https://github.com/sqlite/sqlite
          cd sqlite
          ./configure
          make amalgamation-tarball
          mv sqlite-autoconf-*.tar.gz /Users/runner/
          cd /Users/runner/
          tar -xvf sqlite-autoconf-*.tar.gz
          cd sqlite-autoconf-*/
          export MACOSX_DEPLOYMENT_TARGET=10.13
          export CPPFLAGS="-mmacosx-version-min=10.13"
          export LDFLAGS="-mmacosx-version-min=10.13"
          export CFLAGS="-arch x86_64 -arch arm64"
          export CPPFLAGS=" -DSQLITE_ENABLE_API_ARMOR=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_SNAPSHOT=1 -DSQLITE_ENABLE_SOUNDEX=1 -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_MAX_ATTACHED=125 -DSQLITE_MAX_VARIABLE_NUMBER=250000 -DSQLITE_USE_URI=1"
          ./configure --prefix=/Users/runner/sqlite-prefix/ --disable-dependency-tracking --enable-dynamic-extensions --disable-readline --disable-editline
          make
          make install

      - name: Configure build
        run: |
          if [ "${{ inputs.NIGHTLY }}" = "true" ]; then
            if [ "${{ matrix.sqlcipher }}" = "1" ]; then
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLCipher Nightly"/' config/platform_apple.cmake
            else
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLite Nightly"/' config/platform_apple.cmake
            fi
          else
            if [ "${{ matrix.sqlcipher }}" = "1" ]; then
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLCipher-dev-'$(git rev-parse --short --verify HEAD)'"/' config/platform_apple.cmake
            else
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLite-dev-'$(git rev-parse --short --verify HEAD)'"/' config/platform_apple.cmake
            fi
          fi

          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DcustomTap=1 -DENABLE_TESTING=ON -Dsqlcipher=${{ matrix.sqlcipher }} ..

      - name: Build
        working-directory: ./build
        run: ninja

      - name: Tests
        working-directory: ./build
        run: ninja test

      - name: Build Extension
        run: clang -I /opt/homebrew/opt/sqlb-sqlite/include -L /opt/homebrew/opt/sqlb-sqlite/lib -fno-common -dynamiclib src/extensions/extension-formats.c

      - if: github.event_name != 'pull_request'
        name: Notarization
        id: notarization
        run: chmod +x ./installer/macos/notarize.sh && ./installer/macos/notarize.sh
        env:
          APPLE_ID: ${{ secrets.MACOS_CODESIGN_APPLE_ID }}
          APPLE_PW: ${{ secrets.MACOS_CODESIGN_APPLE_PW }}
          DEV_ID: ${{ secrets.MACOS_CODESIGN_DEV_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYCHAIN_PW: ${{ secrets.MACOS_CODESIGN_KEYCHAIN_PW }}
          P12: ${{ secrets.MACOS_CODESIGN_P12 }}
          P12_PW: ${{ secrets.MACOS_CODESIGN_P12_PW }}
          NIGHTLY: ${{ inputs.NIGHTLY }}
          SQLCIPHER: ${{ matrix.sqlcipher }}
          TEAM_ID: ${{ secrets.MACOS_CODESIGN_TEAM_ID }}

      - if: steps.notarization.conclusion != 'skipped'
        name: Clear Keychain
        run: security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        continue-on-error: true

      - if: github.event_name != 'pull_request'
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.sqlcipher }}
          path: DB.Browser.for.*.dmg
